import pyautogui

#tab 1
pyautogui.keyDown('ctrl')  
pyautogui.keyDown('shift')
pyautogui.press('t')
pyautogui.keyUp('ctrl')   
pyautogui.keyUp('shift')
#rename tab2
pyautogui.keyDown('alt')  
pyautogui.keyDown('shift')
pyautogui.press('s')   
pyautogui.keyUp('alt')
pyautogui.keyUp('shift')
pyautogui.write('tun0')
pyautogui.press('enter')

#tab 2
pyautogui.keyDown('ctrl')  
pyautogui.keyDown('shift')
pyautogui.press('t')
pyautogui.keyUp('ctrl')   
pyautogui.keyUp('shift')
#rename tab2
pyautogui.keyDown('alt')  
pyautogui.keyDown('shift')
pyautogui.press('s')   
pyautogui.keyUp('alt')
pyautogui.keyUp('shift')
pyautogui.write('enum')
pyautogui.press('enter')
#start the tmux session for tab2
pyautogui.write('tmux')
pyautogui.press('enter')
#rename the current session
pyautogui.write('tmux rename-session enum')
pyautogui.press('enter')
pyautogui.write('clear')
pyautogui.press('enter')
#start logging
pyautogui.keyDown('ctrl')
pyautogui.press('b')
pyautogui.keyUp('ctrl')
pyautogui.keyDown('shift')
pyautogui.press('p')
pyautogui.keyUp('shift')

#tab3
pyautogui.keyDown('ctrl')  
pyautogui.keyDown('shift')
pyautogui.press('t')   
pyautogui.keyUp('ctrl')   
pyautogui.keyUp('shift')
#rename tab3
pyautogui.keyDown('alt')  
pyautogui.keyDown('shift')
pyautogui.press('s')   
pyautogui.keyUp('alt')
pyautogui.keyUp('shift')
pyautogui.write('attack')
pyautogui.press('enter')
#start the tmux session for tab3
pyautogui.write('tmux')
pyautogui.press('enter')
#rename the current session
pyautogui.write('tmux rename-session offense')
pyautogui.press('enter')
pyautogui.write('clear')
pyautogui.press('enter')
#start logging
pyautogui.keyDown('ctrl')
pyautogui.press('b')
pyautogui.keyUp('ctrl')
pyautogui.keyDown('shift')
pyautogui.press('p')
pyautogui.keyUp('shift')
#vertical split (qwertz)
pyautogui.keyDown('ctrl')
pyautogui.press('b')
pyautogui.keyUp('ctrl')
pyautogui.keyDown('shift')
pyautogui.press('5')
pyautogui.keyUp('shift')
#start logging
pyautogui.keyDown('ctrl')
pyautogui.press('b')
pyautogui.keyUp('ctrl')
pyautogui.keyDown('shift')
pyautogui.press('p')
pyautogui.keyUp('shift')
#horizontal split (qwertz)
pyautogui.keyDown('ctrl')
pyautogui.press('b')
pyautogui.keyUp('ctrl')
pyautogui.keyDown('shift')
pyautogui.press('2')
pyautogui.keyUp('shift')
#start logging
pyautogui.keyDown('ctrl')
pyautogui.press('b')
pyautogui.keyUp('ctrl')
pyautogui.keyDown('shift')
pyautogui.press('p')
pyautogui.keyUp('shift')